### ISSUE TITLE
java.lang.NoClassDefFoundError: KafkaInstrumentationHelper

### ISSUE THREAD

**Issue by wissam-khair** [elastic/apm-agent-java#1161]
Hi ... I am using Payara 5.194 and applying the configuration in setup [apm-javaagent for payara](https://www.elastic.co/guide/en/apm/agent/java/current/setup-javaagent.html#setup-payara)

My application is consuming/producing Kafka messages, and after applying the configs and restarting Payara server I found the following error message in server.log.

" java.lang.NoClassDefFoundError: co/elastic/apm/agent/kafka/helper/KafkaInstrumentationHelper"

Note: this is only for following versions:
- elastic-apm-agent-1.13.0.jar
- elastic-apm-agent-1.14.0.jar
- elastic-apm-agent-1.15.0.jar

but it is working on elastic-apm-agent-1.12.0.jar

## Logs
```
[2020-04-27T15:31:37.621+0000] [Payara 5.194] [SEVERE] [] [] [tid: _ThreadID=184 _ThreadName=__ejb-thread-pool1] [timeMillis: 1588001497621] [levelValue: 1000] [[
  java.lang.NoClassDefFoundError: co/elastic/apm/agent/kafka/helper/KafkaInstrumentationHelper
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:870)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:856)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:743)
	at com.testapp.module.sender.pipeline.location.LocationMessageProducer.send(LocationMessageProducer.java:109)
	at jdk.internal.reflect.GeneratedMethodAccessor454.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:588)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:408)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4791)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:665)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:836)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.doCall(SystemInterceptorProxy.java:163)
	at com.sun.ejb.containers.interceptors.SystemInterceptorProxy.aroundInvoke(SystemInterceptorProxy.java:140)
	at jdk.internal.reflect.GeneratedMethodAccessor210.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:615)
	at org.jboss.weld.module.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:81)
	at org.jboss.weld.module.ejb.SessionBeanInterceptor.aroundInvoke(SessionBeanInterceptor.java:52)
	at jdk.internal.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:895)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:835)
	at com.sun.ejb.containers.interceptors.InterceptorManager.intercept(InterceptorManager.java:374)
	at com.sun.ejb.containers.BaseContainer.__intercept(BaseContainer.java:4763)
	at com.sun.ejb.containers.BaseContainer.intercept(BaseContainer.java:4751)
	at com.sun.ejb.containers.EjbAsyncTask.call(EjbAsyncTask.java:101)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
]]
```

**Comment by felixbarny** [comment]
Hi and thanks for the report.

Could you please provide the full agent debug logs, as described here?
https://www.elastic.co/guide/en/apm/agent/java/current/trouble-shooting.html

**Comment by wissam-khair** [comment]
Thank you @felixbarny and I'm so sorry, I didn't find out how to make agent push debug logs.. anyway this the first log error.

[2020-04-28T07:16:20.565+0000] [Payara 5.194] [SEVERE] [] [] [tid: _ThreadID=164 _ThreadName=Thread-43] [timeMillis: 1588058180565] [levelValue: 1000] [[
  java.lang.NoClassDefFoundError: co/elastic/apm/agent/kafka/helper/KafkaInstrumentationHeadersHelper
	at org.apache.kafka.clients.consumer.ConsumerRecords.iterator(ConsumerRecords.java:82)
	at java.base/java.lang.Iterable.forEach(Iterable.java:74)
	at com.testapp.messagepipeline.kafka.KafkaConsumerWorker.encapsulateMessages(KafkaConsumerWorker.java:90)
	at com.testapp.messagepipeline.kafka.KafkaConsumerWorker.doOneRound(KafkaConsumerWorker.java:71)
	at com.testapp.messagepipeline.kafka.KafkaConsumerWorker.process(KafkaConsumerWorker.java:52)
	at com.testapp.messagepipeline.kafka.KafkaConsumerWorker.run(KafkaConsumerWorker.java:40)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: co.elastic.apm.agent.kafka.helper.KafkaInstrumentationHeadersHelper
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1687)
	at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1528)
	... 7 more
]]

**Comment by eyalkoren** [comment]
> I didn't find out how to make agent push debug logs..

Did you look in the link provided by @felixbarny ?

How did you install the agent?

**Comment by eyalkoren** [comment]
It seems like an OSGi issue, where the instrumented app code can't see the agent code. I can't say if that's indeed the case, or why you only get that with the Kafka plugin, but since you did not upload the debug log, there is not much we can do.
If you want us to look into this, you would have to upload a full debug log, at least from the startup and until there are some of these errors.
Also, please provide the full configuration you used to run the agent - env variables, system properties, config file, etc.

**Comment by wissam-khair** [comment]
Solved by changing the agent file location... as the kafka consumer/producer thread didn't have access to it.
