### ISSUE TITLE
NoClassDefFoundError: jakarta/servlet/ServletContext logged on Undertow startup

### ISSUE THREAD

**Issue by OrangeDog** [elastic/apm-agent-java#2545]
## Describe the bug
```
java.lang.NoClassDefFoundError: jakarta/servlet/ServletContext
	at co.elastic.apm.agent.servlet.servicename.ServletContainerInitializerServiceNameInstrumentation$JakartaInitServiceNameInstrumentation$AdviceClass.onEnter(ServletContainerInitializerServiceNameInstrumentation.java:109)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory$Initializer.onStartup(UndertowServletWebServerFactory.java:507)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:204)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:255)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.createManager(UndertowServletWebServerFactory.java:330)
	at org.springframework.boot.web.embedded.undertow.UndertowServletWebServerFactory.getWebServer(UndertowServletWebServerFactory.java:299)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:182)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:160)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:577)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at uk.ac.csrf.dataplatform.DataPlatformApplication.main(DataPlatformApplication.java:16)
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletContext
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader.findClass(ByteArrayClassLoader.java:403)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at net.bytebuddy.dynamic.loading.ByteArrayClassLoader$ChildFirst.loadClass(ByteArrayClassLoader.java:1265)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 19 more
```

## Steps to reproduce
Spring Boot 2.6.5
Undertow 2.2.16
APM Agent 1.30.0
Run the application

## Expected behavior
No errors logged

**Comment by eyalkoren** [comment]
Thanks for reporting.
I believe this has no effect on functionality for you.
Either way, #2546 fixes this issue, so after the next release this error would be eliminated.

**Comment by OrangeDog** [comment]
> this has no effect on functionality for you

The Spring instrumentation still all appears to work, yes.

**Comment by eyalkoren** [comment]
If next release (or latest snapshot released after merging the fix) does not eliminate this error, please feel free to reopen.

**Comment by Vaishnav-puram** [comment]
@eyalkoren **i'm using spring-boot 2.7.6 geting the same error**

Caused by: java.lang.NoClassDefFoundError: jakarta/servlet/ServletContext
	at java.base/java.lang.Class.getDeclaredFields0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[na:na]
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:738) ~[spring-core-5.3.24.jar:5.3.24]
	... 27 common frames omitted
Caused by: java.lang.ClassNotFoundException: jakarta.servlet.ServletContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 31 common frames omitted

**Comment by JonasKunz** [comment]
@Vaishnav-puram your stacktrace does not contain any stack frames from the elastic apm java agent. Did you verify that the error does not occur when running without the elastic apm agent?

**Comment by Vaishnav-puram** [comment]
@JonasKunz hey thanks for the reply , but earlier my application was running successfully , later i have upgraded the spring-web alone from to v6.0.0 ie., i've added spring -web dependency separately by avoiding coming from the parent and my parent spring-boot-starter-parent v2.7.6

**Comment by Vaishnav-puram** [comment]
@OrangeDog yes i have tried that too like you said i upgraded spring-boot to 3.0.0 which in turn required me to upgrade spring-data-cassandra  from 3.4.2 to 4.0.0 , the problem is now while running application it says **Since you provided explicit contact points, the local DC must be explicitly set (see basic.load-balancing-policy.local-datacenter in the config, or set it programmatically with SessionBuilder.withLocalDatacenter).**  so i've added the config file in my spring application as 
`   @Bean(destroyMethod = "close")
    public CqlSession session() {
        CqlSession session = CqlSession.builder()
                 .addContactPoint(InetSocketAddress.createUnresolved("[240b:c0xx:xx:xxxx:xxx:x:x:x]", port))
                .withConfigLoader(
                        DriverConfigLoader.programmaticBuilder()
                                .withString(DefaultDriverOption.LOAD_BALANCING_LOCAL_DATACENTER, localDatacenter)
                                .withStringList(
                                        DefaultDriverOption.CONTACT_POINTS,
                                        Collections.singletonList("127.0.0.1:9042"))
                                .withString(DefaultDriverOption.AUTH_PROVIDER_USER_NAME,username)
                                .withString(DefaultDriverOption.AUTH_PROVIDER_PASSWORD,password)
                                .withString(DefaultDriverOption.CONNECTION_INIT_QUERY_TIMEOUT,"10s")
                                .withString(DefaultDriverOption.CONNECTION_CONNECT_TIMEOUT, "20s")
                                .withString(DefaultDriverOption.REQUEST_TIMEOUT, "20s")
                                .withString(DefaultDriverOption.CONTROL_CONNECTION_TIMEOUT, "20s")
                                .withString(DefaultDriverOption.SESSION_KEYSPACE,keyspace)
                                .build())
                .build();
        }
        return session;`
but the problem is locally it  working fine , but in my stg env it's not working as in that env the cassandra has an ipv6 address as contact-points 
`org.springframework.beans. BeanInstantiationException: Failed to instantiate [com.datastax.oss. driver.api.core. CalSession]: Factory method 'session' threw exception with message: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/ [240b: cOe0:102:5dd8:b412:2:1:0]:32758, hostId-null, hashCode=4e9ba6a8): [ com.datastax.oss.driver.api.core.connection.ConnectionInitException:[s0|controllid:0X984419ed,L:/[240b:cOe0:102:5dd7:xxxx:x:x:xxxx]:xxxx-R:/[240b:cOe0:102:5dd8:641x:x:x:xxx:xxxx]Protocolinitializa
tion request, step 1 (OPTIONS): unexpected failure (com.datastax.oss.driver.api.core.connection.ClosedConnectionException: Lost connection to remote peer)]
org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171)~[spring-beans-6.0.2.jar!/:6.0.2]
ora.sprinaframework.beans
factory.support.ConstructorResolverinstantiate(ConstructorResolver.java:648>~[spring-beans-6.0.2.jar!/:6.0.27
62 common frames omitted
aused by: com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node (endPoint=/[240b:cOe0:xxx:xxxx:xxx:x:x:xx:3xxx,hostId-null,hashCode=4e9ba6a8):[com.datastax.oss.driver.api.core.connection.ConnectionInitException:[sO|controllid:0x984419ed,L:/[240b:cOe0:102:5dd7:
xxxx:x:x:xxxx]:xxxx- R:/[240b:c0e0:102:5dd8:xxxx:x:x:x]:xxxx] Protocol initialization request,
step 1 (OPTIONS: unexpected tarlure com.datastax.oss.driver.apt.core.connection.closedconnectiontxceptio
Lost connection to remote peer)`
