### ISSUE TITLE
Wildfly 8 doesn't work with elastic-apm-agent-0.5.1

### ISSUE THREAD

**Issue by lk95jofr** [elastic/apm-agent-java#99]
Hi
I am trying to connect the java-apm-agent to wildfly but notice that wildfly won't run correctly.
If i comment out the -javaagent part wildfly runs normaly.

```
Caused by: java.lang.NoClassDefFoundError: co/elastic/apm/jdbc/StatementInstrumentation
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
        at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:455)
        at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:449)
        at org.postgresql.jdbc.PgConnection.getTransactionIsolation(PgConnection.java:833)
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) [:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_161]
        at org.postgresql.ds.PGPooledConnection$ConnectionHandler.invoke(PGPooledConnection.java:333)
        at com.sun.proxy.$Proxy77.getTransactionIsolation(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) [:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_161]
        at org.postgresql.xa.PGXAConnection$ConnectionHandler.invoke(PGXAConnection.java:166)
        at com.sun.proxy.$Proxy77.getTransactionIsolation(Unknown Source)
        at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.<init>(BaseWrapperManagedConnection.java:197)
        at org.jboss.jca.adapters.jdbc.xa.XAManagedConnection.<init>(XAManagedConnection.java:68)
        at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.newXAManagedConnection(XAManagedConnectionFactory.java:523)
        at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.getXAManagedConnection(XAManagedConnectionFactory.java:496)
```

standalone.conf
```
JBOSS_LOG_MANAGER_LIB="$(echo $JBOSS_HOME/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-*.jar)" # resolve logmanager jar
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_LOG_MANAGER_LIB"
JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.jboss.logmanager.LogManager"


JAVA_OPTS="$JAVA_OPTS -Delastic.apm.service_name=lnk-timetable-wf-b-f11"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.application_packages=se.linkon"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.server_url=http://192.168.72.1:8300"

JAVA_OPTS="$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=10.0.2.15:9090,server=y,suspend=n"
JAVA_OPTS="$JAVA_OPTS -javaagent:/opt/monitoring/elastic-apm-agent-0.5.1.jar"
```

Wildfly 8
elastic-apm-agent-0.5.1.jar
jre-1.8.0-openjdk

/Regards Fredrik

**Comment by alvarolobato** [comment]
Hi, thanks for reporting this issue. This seems to be caused by how Wildfly handles classloading and the special handling `javaagent` has. We will have a look and let you know.

**Comment by KyongSik-Yoon** [comment]
@lk95jofr This problem related with OSGI class loading.
You should configure specific setting to standalone.conf or domain.conf for install java agent.
Maybe you can find parts below.
--
if [ "x$JBOSS_MODULES_SYSTEM_PKGS" = "x" ]; then
   JBOSS_MODULES_SYSTEM_PKGS="org.jboss.byteman"
fi
--

Try attach elastic package to there as like
JBOSS_MODULES_SYSTEM_PKGS="org.jboss.byteman,co.elastic"

So WildFly will load all class of co.elastic package ignoring normal OSGI delegation.

**Comment by lk95jofr** [comment]
Thanks. That solved it.
I added "org.jboss.byteman,co.elastic"

**Comment by felixbarny** [comment]
I'll try to add `co.elastic.apm` to the system properties automatically. I'm reopening to track this.

**Comment by lk95jofr** [comment]
What I added was this, standalone.conf (wildfly/bin)
JBOSS_MODULES_SYSTEM_PKGS="org.jboss.byteman,co.elastic,org.jboss.logmanager"

JBOSS_LOG_MANAGER_LIB="$(echo $JBOSS_HOME/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-*.jar)" # resolve logmanager jar
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_LOG_MANAGER_LIB"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

JAVA_OPTS="$JAVA_OPTS -Delastic.apm.service_name=my-service"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.application_packages=se.my.package"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.server_url=http://localhost:8200"

JAVA_OPTS="$JAVA_OPTS -javaagent:/path/elastic-apm-agent-0.5.1.jar"

**Comment by felixbarny** [comment]
WildFly now works out-of-the-box without any configuration changes apart from adding the `-javaagent` flag 🙂

**Comment by jackshirazi** [comment]
@Nabin0727 please open a separate issue with all the details including configuration and traces
