### PR TITLE
Fix invalid SQS propagation introduced with #3206

### PR DESCRIPTION
**Pull request by JonasKunz**
## What does this PR do?

Fixes a `ClassDefNotFoundError` reported in this [discussion forums thread](https://discuss.elastic.co/t/bug-apm-java-springboot-v1-39-0-no-jvm-metrics-found/339104).

The invocation of the `SQSHelper` was moved behind the span activation to ensure that even if no span is created, baggage propagation still occurs.

This however caused the `SQSHelper` to be invoked for all aws services, including non-sqs ones.

## Checklist

- [x] This is a bugfix
  - [x] I have updated [CHANGELOG.asciidoc](https://github.com/elastic/apm-agent-java/blob/main/CHANGELOG.asciidoc)
  - [ ] I have added tests that would fail without this fix

### CODE REVIEW

**Comment by JonasKunz** [comment]
Fix has been tested and verified by user ([link](https://discuss.elastic.co/t/apm-java-agent-1-40-leads-to-noclassdeffounderror-receivemessagerequest-in-s3-communication-with-aws-java-sdk-v2/339188/3?u=jonas_kunz)).

**Review by jackshirazi — APPROVED** [review]
