### PR TITLE
Add support for WildFly 8-13

### LINKED ISSUE #99: Wildfly 8 doesn't work with elastic-apm-agent-0.5.1
Hi
I am trying to connect the java-apm-agent to wildfly but notice that wildfly won't run correctly.
If i comment out the -javaagent part wildfly runs normaly.

```
Caused by: java.lang.NoClassDefFoundError: co/elastic/apm/jdbc/StatementInstrumentation
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:266)
        at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:455)
        at org.postgresql.jdbc.PgConnection.execSQLQuery(PgConnection.java:449)
        at org.postgresql.jdbc.PgConnection.getTransactionIsolation(PgConnection.java:833)
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) [:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_161]
        at org.postgresql.ds.PGPooledConnection$ConnectionHandler.invoke(PGPooledConnection.java:333)
        at com.sun.proxy.$Proxy77.getTransactionIsolation(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source) [:1.8.0_161]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_161]
        at java.lang.reflect.Method.invoke(Method.java:498) [rt.jar:1.8.0_161]
        at org.postgresql.xa.PGXAConnection$ConnectionHandler.invoke(PGXAConnection.java:166)
        at com.sun.proxy.$Proxy77.getTransactionIsolation(Unknown Source)
        at org.jboss.jca.adapters.jdbc.BaseWrapperManagedConnection.<init>(BaseWrapperManagedConnection.java:197)
        at org.jboss.jca.adapters.jdbc.xa.XAManagedConnection.<init>(XAManagedConnection.java:68)
        at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.newXAManagedConnection(XAManagedConnectionFactory.java:523)
        at org.jboss.jca.adapters.jdbc.xa.XAManagedConnectionFactory.getXAManagedConnection(XAManagedConnectionFactory.java:496)
```

standalone.conf
```
JBOSS_LOG_MANAGER_LIB="$(echo $JBOSS_HOME/modules/system/layers/base/org/jboss/logmanager/main/jboss-logmanager-*.jar)" # resolve logmanager jar
JAVA_OPTS="$JAVA_OPTS -Xbootclasspath/p:$JBOSS_LOG_MANAGER_LIB"
JAVA_OPTS="$JAVA_OPTS -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.manager=org.jboss.logmanager.LogManager"


JAVA_OPTS="$JAVA_OPTS -Delastic.apm.service_name=lnk-timetable-wf-b-f11"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.application_packages=se.linkon"
JAVA_OPTS="$JAVA_OPTS -Delastic.apm.server_url=http://192.168.72.1:8300"

JAVA_OPTS="$JAVA_OPTS -Xdebug -Xrunjdwp:transport=dt_socket,address=10.0.2.15:9090,server=y,suspend=n"
JAVA_OPTS="$JAVA_OPTS -javaagent:/opt/monitoring/elastic-apm-agent-0.5.1.jar"
```

Wildfly 8
elastic-apm-agent-0.5.1.jar
jre-1.8.0-openjdk

/Regards Fredrik

### PR DESCRIPTION
**Pull request by felixbarny**
* Includes integration tests
* Replace usage of java.util.logging with slf4j simplelogger,
  as WildFly does not like JUL
* Adds co.elastic.apm as system packages to work around
  module class loader issues

closes #99

### CODE REVIEW

**Comment by felixbarny** [comment]
Relates to #65
